name: qbox_authorization
description: A simple Flutter authentication package with login screen and provider support.
version: 0.0.9
homepage: https://github.com/jahongirdev1/qbox_authorization
repository: https://github.com/jahongirdev1/qbox_authorization
issue_tracker: https://github.com/jahongirdev1/qbox_authorization/issues
documentation: https://github.com/jahongirdev1/qbox_authorization

environment:
  sdk: ^3.6.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.8.0+1
  provider: ^6.1.2
  flutter_svg: ^2.0.14

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
